baseURL = "https://peski-sys.github.io/blog-site/"
locale = "en-US"
title = "Saugat's Blog"
theme = "paper"

enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[pagination]
  pagerSize = 5

[params]
  color = "linen"
  description = "A research blog."
  name = "Blogs"
  bio = "This is a blog of my learnings, experiments, and research writing."
  rss = true
  disableHLJS = true
  disablePostNavigation = true
  monoDarkIcon = true
  math = true
  twitter = 'Saugat_K90'               # twitter.com/YOUR_TWITTER_ID
  github = 'peski-sys'                 # github.com/YOUR_GITHUB_ID  
  direction = "ltr"
  avatar = ''                 # gravatar email or image url
  favicon = ""
  appleTouchIcon = ""
  mainSections = ["posts", "post"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
